# This is a basic workflow to help you get started with Actions
name: Smart Docker Build & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    env:
      AWS_REGION: ap-south-1
      ECR_REPOSITORY: playwright-tests
      IMAGE_TAG: latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Detect file changes
      - name: Detech changes
        id: changes
        run: |
          echo "Checking changed files..."

          if git diff --name-only HEAD~1 | grep -E '^(Dockerfile|src/)';
          then
          echo "build_iamge==true" >> $GITHUB_OUTPUT
          else
          echo "build_image==false" >> $GITHUB_OUTPUT
          fi

      # 3️⃣ Login to ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      # 4️⃣ Build Docker image (ONLY when needed)
      - name: Build docker image
        if: steps.changes.outputs.build_image == 'true'
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG

      # 5️⃣ Tag & Push image (ONLY when needed)
      - name: Push docker image to ECR
        if: steps.changes.outputs.build_image == 'true'
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
